# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d0bbe4f0015d1494de6ad3d77c68e1bb453a513ba02d726060fecf4468f7f898be3d5ef15f097f31f46a86bd7fb18acf578637755b2be64d54560f1ad30b6be

test:
  secret_key_base: 979f8c702c955bc9f92c296ca25e4a985956e68ab9768d342ad49eda9e29c483ea90f346d4626493cc1fa1af2d0d9bccd225f3b904488d87386e9f4e12dc81e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
